trigger:
- master

pool:
  name: 'test'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'privatecontainerregistry'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'azure'
    azureResourceGroup: 'gov-devops'
    kubernetesCluster: 'private-aks-cluster'
    command: 'apply'
    arguments: '-f deploy.yaml'